const dotenv = require("dotenv");

// Utiliza o arquivo .env para obter o accessToken (Importante: nunca mandar o accessToken para o repositório!)
dotenv.config();

const hubspot = require("@hubspot/api-client");
const fs = require("fs");

const translations = {
  "0-1": {
    "First Adoption date": "Data da primeira adoção",
    "First Churn date": "Data do primeiro churn",
    "First Customer date": "Primeira data de cliente",
    "First Lead date": "Primeira data de lead",
    "First Loyalty date": "Data de primeira fidelização",
    "First Marketing assigned date": "Data de primeira atribuição ao marketing ",
    "First meeting complete date": "Data de primeira reunião completa",
    "First meeting create date": "Data de primeira reunião criada",
    "First meeting no show date": "Data de primeiro no show",
    "First meeting set date": "Data de primeira reunião marcada",
    "First MQL date": "Data de primeiro MQL",
    "First Opportunity date": "Data de primeira Oportunidade",
    "First Pre-Sales assigned date": "Data de primeira atribuição contract termination datea pre-sales",
    "First recycle date": "Data de primeira reciclagem",
    "First Sales Acquisition assigned date": "Data de primeira atribuição para Sales Acquisition",
    "First Sales Expansion assigned date": "Data de primeira atribuição para Sales Expansion",
    "First Sales Retention assigned date": "Data de primeira atribuição para Sales Retention",
    "First Service Onboarding assigned date": "Data de primeira atribuição para Onboarding",
    "First Service Ongoing assigned date": "Data de primeira atribuição para Ongoing",
    "First SQL date": "Date de primeiro SQL",
    "First Support L1 assigned date": "Data de primeira atribuição para Suporte L1",
    "First Support L2 assigned date": "Data de primeira atribuição para Suporte L2",
    "Latest (BOFU) conversion date": "Última data de conversão (BOFU)",
    "Latest (MOFU) conversion date": "Última data de conversão (MOFU)",
    "Latest (TOFU) conversion date": "Última data de conversão (TOFU)",
    "Latest connected date": "Última data de conexão",
    "Latest feedback data": "Última data de feedback",
    "Latest Marketing assigned date": "Última data de atribuição para Marketing",
    "Latest meeting complete date": "Última data de reunião completa",
    "Latest meeting create date": "Última data de reunião criada",
    "Latest meeting no show date": "Última data de no show",
    "Latest meeting set date": "Última data de reunião marcada",
    "Latest pre-sales assigned date": "Última data de atribuição para pré-vendas",
    "Latest recycle date": "Última data de reciclagem",
    "Latest Sales Acquisition assigned date": "Última data de atribuição para Sales Acquisition",
    "Latest Sales Expansion assigned date": "Última data de atribuição para Sales Expansion",
    "Latest Sales Retention assigned date": "Última data de atribuição para Sales Retention",
    "Latest Service Onboarding assigned date": "Última data de atribuição para Onboarding",
    "Latest Service Ongoing assigned date": "Última data de atribuição para Ongoing",
    "Latest Support L1 assigned date": "Última data de atribuição para Suporte L1",
    "Latest Support L2 assigned date": "Última data de atribuição para Suporte L2",
    "Latest unqualified date": "Última data de desqualificação",
    "Latest worked date": "Última data trabalhada",
    "Lead date": "Data de Lead",
    "Loyalty date": "Data de Fidelidade",
    "MQL date": "Data de MQL",
    "Negotiation date": "Data de negociação",
    "Opportunity date": "Data de Oportunidade",
    "Proposal presented date": "Data de prospota apresentada",
    "SQL date": "Data de SQL",
    "Today's date": "Data de hoje",
    "First Lifecycle stage": "Primeiro estágio do ciclo de vida",
    "Lifecycle stage (Checkboxes)": "Estágio do ciclo de vida (checkboxes)",
    "Lost lifecycle drill down 1": "Detalhamento 1 do ciclo de vida perdido",
    "Recent Lifecycle Stage": "Estágio do ciclo de vida recente",
    "Adoption rate": "Taxa de adoção",
    "Churn rate": "Taxa de churn",
    "Connect rate": "Taxa de conexão",
    "Customer rate": "Taxa de cliente",
    "Expansion rate": "Taxa de expansão",
    "Loyalty rate": "Taxa de fidelidade",
    "Meeting no show rate": "Taxa de não comparecimento",
    "Meeting show up rate": "Taxa de comparecimento em reuniões",
    "MQL rate": "Taxa de MQL",
    "Negotiation rate": "Taxa de negociação",
    "Opportunity rate": "Taxa de Oportunidade",
    "Proposal presented rate": "Taxa de proposta apresentada",
    "Recycle rate": "Taxa de reciclagem",
    "Retention rate": "Taxa de retenção",
    "SQL rate": "Taxa de SQL",
    "Unqualified rate": "Taxa de não qualificação",
    "Work rate": "Taxa de trabalho",
    "Time from Adoption to Churn": "Tempo entre adoção e churn",
    "Time from Adoption to Loyalty": "Tempo entre adoção e fidelização",
    "Time from Create to Lead": "Tempo entre criação e lead",
    "Time from Customer to Adoption": "Tempo entre cliente e adoção",
    "Time from Customer to Churn": "Tempo entre cliente e churn",
    "Time from Customer to Loyalty": "Tempo entre cliente e fidelização",
    "Time from Lead to Connected": "Tempo entre lead e conectado",
    "Time from Lead to Customer": "Tempo entre lead e cliente",
    "Time from Lead to Lost": "Tempo entre lead e perdido",
    "Time from Lead to Meeting set": "Tempo entre lead e reunião marcada",
    "Time from Lead to MQL": "Tempo entre lead e MQL",
    "Time from Lead to Opportunity": "Tempo entre lead e oportunidade",
    "Time from Lead to SQL": "Tempo entre lead e SQL",
    "Time from Lead to Unqualified": "Tempo entre lead e não qualificado",
    "Time from Lead to Worked": "Tempo entre lead e trabalhado",
    "Time from Loyalty to Churn": "Tempo entre fidelização e churn",
    "Time from meeting create to complete": "Tempo entre reunião criada e completa",
    "Time from meeting create to set": "Tempo entre reunião criada e marcada",
    "Time from meeting set to complete": "Tempo entre reunião criada e completa",
    "Time from MQL to Customer": "Tempo entre MQL e cliente",
    "Time from MQL to Opportunity": "Tempo entre MQL e oportunidade",
    "Time from MQL to SQL": "Tempo entre MQL e SQL",
    "Time from Opportunity to Customer": "Tempo entre oportunidade e cliente",
    "Time from SQL to Customer": "Tempo entre SQL e cliente",
    "Time from SQL to Opportunity": "Tempo entre SQL e oportunidade",
    "Brazil state list": "Lista de estados do Brasil",
    "Buying Role": "Cargo de compra",
    "Canceled products": "Produtos cancelados",
    Continent: "Continente",
    "Country list": "Lista de países",
    "Desired Products": "Produtos desejados",
    "Email Status": "Status do email",
    "Ideal Customer Profile Tier (ICP)": "Tier de perfil de cliente ideal",
    "Industry segment (list)": "Segmento da indústria (lista)",
    "Job Role": "Cargo de Trabalho",
    "Latest Product A amount": "Última quantidade do produto A",
    "Latest Product B amount": "Última quantidade do produto B",
    "Latest Product C amount": "Última quantidade do produto C",
    "Latest purchased products": "Últimos produtos comprados",
    "Lead priority": "Prioridade do Lead",
    "Linkedin Profile URL": "URL do perfil do Linkedin",
    "Monthly revenue (list)": "Receita mensal (lista)",
    Need: "Necessidade",
    "Needs description": "Descrição das necessidades",
    "Number of associated leads": "Número de leads associados",
    "Number of associated tickets (base)": "Número de tickets associados (base)",
    "Number of associated tickets (workflow)": "Número de tickets associados (workflows)",
    "Number of employees (list)": "Número de funcionários (lista)",
    "Number of employees (number)": "Número de funcionários (número)",
    Objection: "Objeção",
    "Objections description": "Descrição das objeções",
    Timing: "Timing",
    "Unqualified reason": "Razão de não qualificação",
    "Engagement feedback (list)": "Feedback de engajamento (lista)",
    "Engagement feedback details": "Detalhes sobre o feedback de engajamento",
    "Engagement score": "Score de engajamento",
    "Copy reset trigger": "Copiar gatilho de redefinição",
    "Expansion trigger": "Gatilho de expansão",
    "First Lifecycle trigger": "Primeiro gatilho de ciclo de vida",
    "Sales accepted deal trigger": "Gatilho de deal aceito por vendas",
    "SLA Lead Reset Trigger": "Gatilho de reset do SLA do Lead",
    "Status change SLA trigger": "Gatilho de mudança de status",
    "Ticket association trigger": "Gatilho dfe associação de ticket",
    "Ticket support trigger for Lifecycle": "Gatilho de suporte para o ciclo de vida do ticket",
    "Valid activity SLA trigger": "Gatilho de atividade válida para o SLA",
    "Churn reason (list)": "Motivo de Churn (lista)",
    "Churn type": "Tipo de Churn",
    "Client status": "Status do Cliente",
    "Commercial event": "Evento comercial",
    "Company address": "Endereço da empresa",
    "Company tax": "Imposto da empresa",
    "Contact tax": "Imposto do contato",
    "Contract status": "Status do contrato",
    "Current revenue": "Receita atual",
    "Customer lifetime": "Tempo de vida do cliente",
    "Lifetime value": "Valor vitalício",
    "Net revenue growth": "crescimento da receita líquida",
    "Net revenue retention rate": "Taxa de retenção de receita líquida",
    "Starting revenue": "Receita inicial",
  },
  "0-2": {
    "Areas of Owners (list)": "Áreas dos proprietários (lista)",
    "First Owner": "Primeiro proprietário",
    "First Owner Area": "Área do primeiro proprietário",
    "First Pre-Sales Owner": "Primeiro proprietário de pré-vendas",
    "First Pre-Sales Team": "Primeiro time de pré-vendas",
    "First Sales Acquisition Owner": "Primeiro proprietário de Sales Acquisition",
    "First Sales Acquisition Team": "Primeiro time de Sales Acquisition",
    "First Sales Expansion Owner": "Primeiro proprietário de Sales Expansion",
    "First Sales Expansion Team": "Primeiro time de Sales Expansion",
    "First Sales Retention Owner": "Primeiro proprietário de Sales Retention",
    "First Sales Retention Team": "Primeiro time de Sales Retention",
    "First Service Onboarding Owner": "Primeiro proprietário de Onboarding",
    "First Service Onboarding Team": "Primeiro time de Onboarding",
    "First Service Ongoing Owner": "Primeiro proprietário de Ongoing",
    "First Service Ongoing Team": "Primeiro time de Ongoing",
    "First Team": "Primeiro time",
    "HubSpot Team (text)": "Time do HubSpot (texto)",
    "Latest Owner Area": "Área do último proprietário",
    "Marketing Owner": "Proprietário de Marketing",
    "Marketing Team": "Time de Marketing",
    "Owner History String": "Cadeia de histórico do proprietário",
    "Recent Pre-Sales Owner": "Proprietário recente de pré-vendas",
    "Recent Pre-Sales Team": "Time recente de pré-vendas",
    "Recent Sales Acquisition Owner": "Proprietário recente de Sales Acquisition",
    "Recent Sales Acquisition Team": "Time recente de Sales Acquisition",
    "Recent Sales Expansion Owner": "Proprietário recente de Sales Expansion",
    "Recent Sales Expansion Team": "Time recente de Sales Expansion",
    "Recent Sales Retention Owner": "Proprietário recente de Sales Retention",
    "Recent Sales Retention Team": "Time recente de Sales Retention",
    "Recent Service Onboarding Owner": "Proprietário recente de Onboarding",
    "Recent Service Onboarding Team": "Time recente de Onboarding",
    "Recent Service Ongoing Owner": "Proprietário recente de Ongoing",
    "Recent Service Ongoing Team": "Time recente de Ongoing",
    "Service Support L1 Owner": "Proprietário de suporte L1",
    "Service Support L1 Team": "Time de suporte L1",
    "Service Support L2 Owner": "Proprietário de suporte L2",
    "Service Support L2 Team": "Time de suporte L2",
    "Audience identifier": "Identificador de Audiência",
    "Campaign identifier": "Identificador de Campanha",
    "Content funnel stage": "Fase do funil de conteúdo",
    "Content type": "Tipo de conteúdo",
    "Conversion history string": "Cadeia de histórico de conversão",
    "Creative identifier": "Identificador criativo",
    "Data enrichment": "Enriquecimento dos dados",
    "Data extractor": "Extrator de dados",
    "First macro source": "Primeira fonte macro",
    "First source (remap)": "Primeira fonte (remap)",
    "First source drill-down 1 (remap)": "Detalhamento 1 da primeira fonte (remap)",
    "First source drill-down 2 (remap)": "Detalhamento 2 da primeira fonte (remap)",
    "Health score": "Score de saúde",
    "Latest macro source": "Última fonte macro",
    "Latest source (remap)": "Última fonte (remap)",
    "Latest source drill-down 1 (remap)": "Detalhamento 1 da última fonte (remap)",
    "Latest source drill-down 2 (remap)": "Detalhamento 2 da última fonte (remap)",
    "Lead score": "Score do Lead",
    "Macro source": "Fonte macro",
    "Outbound source drill-down 1": "Detalhamento 1 da fonte Outbound",
    "Outbound source drill-down 1 (open)": "Detalhamento 1 da fonte Outbound (aberto)",
    "Source list (remap)": "Lista de fontes (remap)",
    "Adoption complete date": "Data de adoção completa",
    "Adoption date": "Data de adoção",
    "Adoption start date": "Data de início da adoção",
    "Churn date": "Data de churn",
    "Contract sent date": "Data de envio de contrato",
    "Contract signed date": "Data de assinatura de contrato",
    "Contract termination date": "Data de rescição do contrato",
    "Create date": "Data de criação",
    "Create date (remap)": "Data de criação (remap)",
    "Customer date": "Data de cliente",
    "First (BOFU) conversion date": "Data da primeira conversão (BOFU)",
    "First (MOFU) conversion date": "Data da primeira conversão (MOFU)",
    "First (TOFU) conversion date": "Data da primeira conversão (TOFU)",
    "First Adoption date": "Data da primeira adoção",
    "First Churn date": "Data do primeiro churn",
    "First Customer date": "Primeira data de cliente",
    "First Lead date": "Primeira data de lead",
    "First Loyalty date": "Data de primeira fidelização",
    "First Marketing assigned date": "Data de primeira atribuição ao marketing ",
    "First meeting complete date": "Data de primeira reunião completa",
    "First meeting create date": "Data de primeira reunião criada",
    "First meeting no show date": "Data de primeiro no show",
    "First meeting set date": "Data de primeira reunião marcada",
    "First MQL date": "Data de primeiro MQL",
    "First Opportunity date": "Data de primeira Oportunidade",
    "First Pre-Sales assigned date": "Data de primeira atribuição contract termination datea pre-sales",
    "First recycle date": "Data de primeira reciclagem",
    "First Sales Acquisition assigned date": "Data de primeira atribuição para Sales Acquisition",
    "First Sales Expansion assigned date": "Data de primeira atribuição para Sales Expansion",
    "First Sales Retention assigned date": "Data de primeira atribuição para Sales Retention",
    "First Service Onboarding assigned date": "Data de primeira atribuição para Onboarding",
    "First Service Ongoing assigned date": "Data de primeira atribuição para Ongoing",
    "First SQL date": "Date de primeiro SQL",
    "First Support L1 assigned date": "Data de primeira atribuição para Suporte L1",
    "First Support L2 assigned date": "Data de primeira atribuição para Suporte L2",
    "Latest (BOFU) conversion date": "Última data de conversão (BOFU)",
    "Latest (MOFU) conversion date": "Última data de conversão (MOFU)",
    "Latest (TOFU) conversion date": "Última data de conversão (TOFU)",
    "Latest CES date": "Data da última CES",
    "Latest connect date": "Data da última conexão",
    "Latest CSat date": "Data do último CSAT",
    "Latest feedback data": "Data do último feedback",
    "Latest Marketing assigned date": "Última data de atribuição para Marketing",
    "Latest meeting complete date": "Última data de reunião completa",
    "Latest meeting create date": "Última data de reunião criada",
    "Latest meeting no show date": "Última data de no show",
    "Latest meeting set date": "Última data de reunião marcada",
    "Latest NPS date": "Data do último NPS",
    "Latest open deal date": "Data do último deal aberto",
    "Latest pre-sales assigned date": "Última data de atribuição para pré-vendas",
    "Latest recycle date": "Última data de reciclagem",
    "Latest Sales Acquisition assigned date": "Última data de atribuição para Sales Acquisition",
    "Latest Sales Expansion assigned date": "Última data de atribuição para Sales Expansion",
    "Latest Sales Retention assigned date": "Última data de atribuição para Sales Retention",
    "Latest Service Onboarding assigned date": "Última data de atribuição para Onboarding",
    "Latest Service Ongoing assigned date": "Última data de atribuição para Ongoing",
    "Latest Support L1 assigned date": "Última data de atribuição para Suporte L1",
    "Latest Support L2 assigned date": "Última data de atribuição para Suporte L2",
    "Latest unqualified date": "Última data de desqualificação",
    "Latest worked date": "Última data trabalhada",
    "Lead date": "Data de Lead",
    "Lost date": "Data de perdido",
    "Loyalty date": "Data de Fidelidade",
    "MQL date": "Data de MQL",
    "Negotiation date": "Data de negociação",
    "Opportunity date": "Data de Oportunidade",
    "Proposal presented date": "Data de prospota apresentada",
    "SQL date": "Data de SQL",
    "Today's date": "Data de hoje",
    "First Lifecycle stage": "Primeiro estágio do ciclo de vida",
    "Lead Status": "Status do Lead",
    "Lifecycle Stage": "Estágio do ciclo de vida",
    "Lifecycle Stage (Checkboxes)": "Estágio do ciclo de vida (checkbox)",
    "Lost lifecycle drill down 1": "Detalhamento 1 do ciclo de vida perdido",
    "Recent Lifecycle Stage": "Estágio do ciclo de vida recente",
    "Adoption rate": "Taxa de adoção",
    "Churn rate": "Taxa de churn",
    "Connect rate": "Taxa de conexão",
    "Customer rate": "Taxa de cliente",
    "Expansion rate": "Taxa de expansão",
    "Loyalty rate": "Taxa de fidelidade",
    "Meeting show up rate": "Taxa de comparecimento em reuniões",
    "MQL rate": "Taxa de MQL",
    "Negotiation rate": "Taxa de negociação",
    "Opportunity rate": "Taxa de Oportunidade",
    "Proposal presented rate": "Taxa de proposta apresentada",
    "Recycle rate": "Taxa de reciclagem",
    "Retention rate": "Taxa de retenção",
    "SQL rate": "Taxa de SQL",
    "Unqualified rate": "Taxa de não qualificação",
    "Work rate": "Taxa de trabalho",
    "Time from Adoption to Churn": "Tempo entre adoção e churn",
    "Time from Adoption to Loyalty": "Tempo entre adoção e fidelização",
    "Time from Create to Lead": "Tempo entre criação e lead",
    "Time from Customer to Adoption": "Tempo entre cliente e adoção",
    "Time from Customer to Churn": "Tempo entre cliente e churn",
    "Time from Customer to Loyalty": "Tempo entre cliente e fidelização",
    "Time from Lead to Customer": "Tempo entre lead e cliente",
    "Time from Lead to Lost": "Tempo entre lead e perdido",
    "Time from Lead to MQL": "Tempo entre Lead e MQL",
    "Time from Lead to Negotiation": "Tempo entre Lead e Negociação",
    "Time from Lead to Opportunity": "Tempo entre Lead e Oportunidade",
    "Time from Lead to Proposal sent": "Tempo entre lead e proposta enviada",
    "Time from Lead to SQL": "Tempo entre lead e SQL",
    "Time from Lead to Unqualified": "Tempo entre lead e não qualificado",
    "Time from Loyalty to Churn": "Tempo entre fidelização e churn",
    "Time from meeting create to complete": "Tempo entre reunião criada e completa",
    "Time from meeting create to set": "Tempo entre reunião criada e marcada",
    "Time from meeting set to complete": "Tempo entre reunião criada e completa",
    "Time from MQL to Customer": "Tempo entre MQL e cliente",
    "Time from MQL to Opportunity": "Tempo entre MQL e oportunidade",
    "Time from MQL to SQL": "Tempo entre MQL e SQL",
    "Time from Opportunity to Customer": "Tempo entre oportunidade e cliente",
    "Time from Opportunity to Lost": "Tempo entre oportunidade e perdido",
    "Time from Opportunity to Negotiation": "Tempo entre oportunidade e negociação",
    "Time from Opportunity to Proposal sent": "Tempo entre oportunidade e proposta enviada",
    "Time from SQL to Customer": "Tempo entre SQL e cliente",
    "Time from SQL to Opportunity": "Tempo entre SQL e oportunidade",
    "Time from start to complete adoption": "Tempo entre início da adoção e adoção completa",
    "Brazil state list": "Lista de estados do Brasil",
    "Canceled products": "Produtos Cancelados",
    "Company type": "Tipo da empresa",
    Continent: "Continente",
    "Country list": "Lista de países",
    "Crunch base Profile URL": "URL do perfil na crunch base",
    "Desired Products": "Produtos desejados",
    "Ideal Customer Profile Tier (ICP)": "Tier de perfil de cliente ideal",
    "Industry segment (list)": "Segmento da indústria (lista)",
    "Last funding currency": "Última moeda de financiamento",
    "Last funding date": "Última data de financiamento",
    "Last funding investor": "Últim investidor de financiamento",
    "Last funding raised": "Último financiamento levantada",
    "Last funding type": "Último tipo de financiamento",
    "Latest amounts update": "Atulização de últimas quantia",
    "Latest Product A amount": "Última quantidade do produto A",
    "Latest Product B amount": "Última quantidade do produto B",
    "Latest Product C amount": "Última quantidade do produto C",
    "Latest purchased products": "Últimos produtos comprados",
    "Linkedin Bio": "Bio do Linkedin",
    "Linkedin Company Page": "Página do Linkedin da Empresa",
    "Monthly revenue (list)": "Receita mensal (lista)",
    Need: "Necessidade",
    "Number of associated tickets": "Número de tickets associados",
    "Number of employees (list)": "Número de funcionários (lista)",
    Objection: "Objeção'",
    Priority: "Prioridade",
    Timing: "Timing",
    "Unqualified Reason": "Razão da não qualificação",
    "Feedback history": "Histórico de feedback",
    "Monthly CES count": "Contagem mensal de CES",
    "Monthly CES points": "Pontos mensais de CES",
    "Monthly CES rating": "Avaliação mensal de CES",
    "Monthly CSAT count": "Contagem mensal de CSAT",
    "Monthly CSAT points": "Pontos mensais de CSAT",
    "Monthly CSAT rating": "Avaliação mensal de CSAT",
    "Previous NPS result": "Resultado do último NPS",
    "Recent CES result": "Resultado do CES recente",
    "Recent CSAT result": "Resultado do CSAT recente",
    "Recent NPS result": "Resultado do NPS recente",
    "Total NPS count": "Contagem de NPS total",
    "Churn reason (list)": "Razão de Churn (lista)",
    "Churn type": "Tipo de churn",
    "Client status": "Status do cliente",
    "Commercial event": "Evento comercial",
    "Company address": "Endereço da empresa",
    "Company legal name": "Nome legal da empresa",
    "Company tax ID": "CPF da empresa",
    "Contract status": "Status do contrato",
    "Current revenue": "Receita atual",
    "Customer lifetime": "Tempo de vida do cliente",
    "Expansion trigger": "Gatilho de expansão",
    "Lifetime value": "Valor vitalício",
    "Net revenue growth": "crescimento da receita líquida",
    "Net revenue retention rate": "Taxa de retenção de receita líquida",
    "Product portfolio": "Portfolio de produtos",
    "Starting revenue": "Receita incial",
    "Actual amount trigger": "Gatilho de quantia atual",
    "Company status workflow exclusion trigger": "Gatilho de exclusão do workflow de status de empresa",
    "Copy reset trigger": "Copiar gatilho de redefinição",
    "First Lifecycle Trigger": "Gatilho de primeiro ciclo de vida",
    "Lifecycle workflow exclusion trigger": "Gatilho de exclusão do workflow de ciclo de vida",
    "Number of associated leads": "Número de leads associados",
    "Portfolio Associated Trigger": "Gatilho de portfolio associado",
    "Sales accepteed deal trigger": "Gatilho de deal aceito por vendas",
    "Status change SLA trigger": "Gatilho de SLA de mudança de status",
    "Valid activity SLA trigger": "Gatilho de SLA de atividade válida",
  },
  "0-3": {
    "First Owner": "Primeiro proprietário",
    "First Team": "Primeiro time",
    "HubSpot team (text)": "Time do HubSpot (texto)",
    "Marketing Owner": "Proprietário de Marketing",
    "Marketing Team": "Time de Marketing",
    "Owner History String": "Cadeia de histórico do proprietário",
    "Pre-Sales Owner": "Proprietário de pré-vendas",
    "Pre-Sales Team": "Time de pré-vendas",
    "Sales Acquisition Owner": "Proprietário de Sales Acquisition",
    "Sales Acquisition Team": "Time de Sales Acquisition",
    "Sales Expansion Owner": "Proprietário de Sales Expansion",
    "Sales Expansion Team": "Time de Sales Expansion",
    "Sales Retention Owner": "Proprietário de Sales Retention",
    "Sales Retention Team": "Time de Sales Retention",
    "Service Onboarding Owner": "Proprietário de Onboarding",
    "Service Onboarding Team": "Time de Onboarding",
    "Service Ongoing Owner": "Proprietário de Ongoing",
    "Service Ongoing Team": "Time de Ongoing",
    "Audience identifier": "Identificador de Audiência",
    "Campaign identifier": "Identificador de Campanha",
    "Content funnel stage": "Fase do funil de conteúdo",
    "Content type": "Tipo de conteúdo",
    "Conversion history": "Histórico de conversão",
    "Creative identifier": "Identificador criativo",
    "First macro source": "Primeira fonte macro",
    "First source (remap)": "Primeira fonte (remap)",
    "First source drill-down 1 (remap)": "Detalhamento 1 da primeira fonte (remap)",
    "First source drill-down 2 (remap)": "Detalhamento 2 da primeira fonte (remap)",
    "Forecast submitted copy": "Previsão de cópia enviada",
    "Forecast time accuracy": "Precisão da previsão de tempo",
    "Latest macro source": "Última fonte macro",
    "Latest source (reamp)": "Última fonte (remap)",
    "Latest source drill-down 1 (remap)": "Detalhamento 1 da última fonte (remap)",
    "Latest source drill-down 2 (remap)": "Detalhamento 2 da última fonte (remap)",
    "Machine learning scoring": "Pontuação de aprendizado de máquina",
    "Machine learning scoring (closed lost)": "Pontuação de aprendizado de máquina (perdido)",
    "Machine learning scoring (closed won)": "Pontuação de aprendizado de máquina (ganho)",
    "Machine learning scoring (contract sent)": "Pontuação de aprendizado de máquina (contrato enviado)",
    "Machine learning scoring (forecasting)": "Pontuação de aprendizado de máquina (previsão)",
    "Machine learning scoring (meeting complete)": "Pontuação de aprendizado de máquina (reunião completa)",
    "Machine learning scoring (meeting set)": "Pontuação de aprendizado de máquina (reunião marcada)",
    "Machine learning scoring (negotiation)": "Pontuação de aprendizado de máquina (negociação)",
    "Macro source": "Fonte macro",
    "Marketing action": "Ação de marketing",
    "Outbound source drill-down 1": "Detalhamento 1 da fonte Outbound",
    "Source list (remap)": "Lista de fontes (remap)",
    "Campaign identifier": "Identificador de Campanha",
    utm_content: "utm_conteúdo",
    utm_medium: "utm_meio",
    utm_source: "utm_fonte",
    utm_term: "utm_termo",
    "Churn request date": "Data do pedido de cancelamento",
    "Contract sent date": "Data de contrato enviado",
    "Contract sign date": "Data de contrato assinado",
    "Contract termination date": "Data de finalização de contrato",
    "Create date (remap)": "Data de criação (remap)",
    "First meeting complete date": "Data da primeira reunião completa",
    "First meeting create date": "Data da primeira reunião criada",
    "First meeting no show date": "Data de primeiro não comparecimento",
    "First meeting set date": "Data de primeira reunião marcada",
    "Forecast submit date": "Data de previsão de envio",
    "Forecasted close date": "Data de fechamento prevista",
    "Latest meeting complete date": "Data de última reunião completa",
    "Latest meeting create date": "Data de última reunião criada",
    "Latest meeting no show date": "Data de último não comparecimento",
    "Latest meeting set date": "Data de última reunião marcada",
    "Lost date": "Data de perdido",
    "Negotiation date": "Data de negociação",
    "Next step date": "Data de próximo passo",
    "Opportunity date": "Data de oportunidade",
    "Proposal presented date": "Data de proposta apresentada",
    "Renewal date": "Data de renovação",
    "Today's date": "Data de hoje",
    "Win date": "Data de ganho",
    "Deal status": "Status do negócio",
    "Latest deal stage": "Última etapa do negócio",
    "Lost lifecycle drill-down 1": "Detalhamento 1 do ciclo de vida perdido",
    "Renewal cycle count": "Contagem de ciclo de renovação",
    "Churn rate": "Taxa de churn",
    "Contract sent rate": "Taxa de contrato enviado",
    "Expansion rate": "Taxa de expansão",
    "Lost rate": "Taxa de perdido",
    "Loyalty rate": "Taxa de fidelidade",
    "Meeting no show rate": "Taxa de não comparecimento",
    "Meeting show up rate": "Taxa de comparecimento em reuniões",
    "Negotiation rate": "Taxa de negociação",
    "Opportunity rate": "Taxa de oportunidade",
    "Proposal presented rate": "Taxa de proposta apresentada",
    "Renewal rate": "Taxa de renovação",
    "Retention rate": "Taxa de retenção",
    "Win rate": "Taxa de ganho",
    "Time from Created to Forecasted close": "Tempo entre criação e previsão de fechamento",
    "Time from Created to Lost": "Tempo entre criação e perdido",
    "Time from Created to Negotiation": "Tempo entre criação e negociação",
    "Time from Created to Opportunity": "Tempo entre criação e oportunidade",
    "Time from Created to Proposal sent": "Tempo entre criação e proposta enviada",
    "Time from Created to Win": "Tempo entre criação e ganho",
    "Time from meeting set to complete": "Tempo entre reunião marcada e completa",
    "Time from Opportunity to Lost": "Tempo entre oportunidade e perdido",
    "Time from Opportunity to negotiation": "Tempo entre oportunidade e negociação",
    "Time from Opportunity to Proposal sent": "Tempo entre oportunidade e proposta enviada",
    "Time from Opportunity to Win": "Tempo entre oportunidade e ganho",
    "Time from Proposal Presented to Win": "Tempo entre proposta apresentada e ganho",
    "Time until renewal": "Tempo até a renovação",
    "Deal open time (list)": "Tempo de negócio aberto (lista)",
    "Deal lost without activities": "Negócio perdido sem atividades",
    "Meeting no show count (current)": "Contagem de não comparecimento (atual)",
    "Meeting no show count (total)": "Contagem de não comparecimento (total)",
    "Meeting no show history": "Histórico de não comparecimento",
    "SLA history string": "Cadeia de histórico de SLA",
    "Time in same stage (list)": "Tempo no mesmo estágio (lista)",
    "Time in same status (max)": "Tempo no mesmo status (max)",
    "Time waiting first meeting (list)": "Tempo aguardando primeira reunião (lista)",
    "Time without activity (list)": "Tempo sem atividade (lista)",
    "Time without activity (max)": "Tempo sem atividade (max)",
    "Brazil state list": "Lista de estados do Brasil",
    Budget: "Orçamento",
    "Canceled products": "Produtos cancelados",
    "Challenges description": "Descrição dos desafios",
    Continent: "Continente",
    "Country list": "Lista de Países",
    "Customer definition of success": "Definição de sucesso do cliente",
    "Customer tier": "Tier de cliente",
    "Deal priority": "Prioridade do negócio",
    "Desired Products": "Produtos desejados",
    "Ideal Customer Profile Tier (ICP)": "Tier de perfil de cliente ideal",
    "Industry segment (list)": "Segmento da indústria (lista)",
    "Key reminders": "Lembretes chave",
    "Lost reason (list)": "Razão de perdido (lista)",
    "Monthly revenue (list)": "Receita mensal (lista)",
    Need: "Necessidade",
    "Needs description": "Descrição das necessidades",
    "No product fit reason": "Motivo de não ter fit com o produto",
    "Number of associated tickets": "Número de tickets associados",
    "Number of employees (list)": "Número de funcionários (lista)",
    Objection: "Objeção",
    "Objections description": "Descrição das objeções",
    "Product A amount": "Quantidade do produto A",
    "Product B amount": "Quantidade do produto B",
    "Product C amount": "Quantidade do produto C",
    "Purchased products": "Produtos comprados",
    "Reason to choose the competitor": "Razão para escolher a concorrência",
    "Target market": "Mercado alvo",
    Timing: "Timing",
    "Total deal amount": "Quantia total do negócio",
    "Win reason": "Razão de ganho",
    "Churn moment": "Momento de churn",
    "Churn moment (trigger)": "Momento de churn (gatilho)",
    "Churn reason (list)": "Motivo de churn (lista)",
    "Churn reason description": "Descrição do motivo de churn",
    "Deal feedback (list)": "Feedback do negócio (lista)",
    "Deal feedback details": "Detalhes do feedback do negócio",
    "Deal rating": "Avaliação do negócio",
    "Meeting no show reason": "Motivo de não comparecimento",
    "Recovery status ": "Status de recuperação",
    "Retention event type": "Tipo de evento de retenção",
    "Churn reason (trigger)": "Motivo de churn (gatilho)",
    "Churn request trigger": "Pedido de churn (gatilho)",
    "CPQ phantom trigger": "Gatilho fantasma CPQ",
    "Meeting show up trigger": "Gatilho de comparecimento à reunião",
    "Onboarding trigger": "Gatilho de Onboarding",
    "Recovery date trigger": "Gatilho de data de recuperação",
    "Recycle trigger": "Gatilho de reciclagem",
    "Sales accepted deal trigger": "Gatilho de deal aceito por vendas",
    "Stage change SLA trigger": "Gatilho de SLA de mudança de estágio",
    "Strategic Customer Trigger": "Gatilho de cliente estratégico",
    "Valid activity SLA trigger": "Gatilho de atividade válida",
    "% of discount": "% de desconto",
    City: "Cidade",
    "Commercial event": "Evento comercial",
    "Company address": "Endereço da empresa",
    "Company legal name": "Nome legal da empresa",
    "Company postal code": "Código postal da empresa",
    "Company tax ID": "CPF da empresa",
    "Contract status": "Status do contrato",
    "Current revenue": "Receita atual",
    "Customer lifetime": "Tempo de vida do cliente",
    "Customer lifetime value": "Valor vitalício do cliente",
    "Deal lifetime": "Tempo de vida do negócio",
    "Deal lifetime value": "Valor vitalício do negócio",
    "Deliquency amount": "Valor da inadimplência",
    "Deliquency payments": "Pagamentos inadimplentes",
    "Deliquency rate": "Taxa de inadimplência",
    "Finance email": "Email do financeiro",
    "Finance point of contact job role": "Cargo do ponto focal do financeiro",
    "Finance point of contact name": "Nome do ponto focal do financeiro",
    "Key notes for accounting": "Notas importantes para contabilidade",
    "Net revenue growth": "Crescimento da receita líquida",
    "Net revenue retention rate": "Taxa de retenção de receita líquida",
    "Payment start date": "Data de início do pagamento",
    "Payment frequency": "Frequência de pagamento",
    "Payment method": "Método de pagamento",
    "Starting revenue": "Receita inicial",
    "Subscription discounted price": "Preço da assinatura com desconto",
    "Subscription start date": "Data de início da assinatura",
  },
};

const func = async () => {
  const hubspotClient = new hubspot.Client({
    accessToken: process.env.accessToken,
  });

  const objectTypesArr = [
    "0-1", // Contact
    "0-2", // Company
    "0-3", // Deal
    // "0-5", // Ticket
  ];

  try {
    for (const objectType of objectTypesArr) {
      const allObjectTypeProperties =
        await hubspotClient.crm.properties.coreApi.getAll(objectType);

      const translationData = translations[objectType];

      let i = 0;

      const translatedKeys = [];

      for (const property of allObjectTypeProperties.results) {
        i++;

        const labelTranslation = Object.entries(translationData).find(
          ([_, value]) => value.toLowerCase() === property.label.toLowerCase()
        )?.[0];

        if (labelTranslation && !property.hubspotDefined) {
          await hubspotClient.crm.properties.coreApi.update(
            objectType,
            property.name,
            { label: labelTranslation }
          );

          console.log(
            `${objectType}: ${i}/${allObjectTypeProperties.results.length} ✅ Propriedade com nome "${property.label}" traduzida para "${labelTranslation}"`
          );

          translatedKeys.push(property.label.toLowerCase());
        } else {
          // console.log(
          //   `${objectType}: ${++i}/${
          //     allObjectTypeProperties.results.length
          //   } 🟡 Tradução não encontrada para "${property.label}"`
          // );
        }
      }

      const notTranslatedKeys = {};

      const newTranslations = await hubspotClient.crm.properties.coreApi.getAll(
        objectType
      );

      for (const [translation, property] of Object.entries(translationData)) {
        if (
          !translatedKeys.some((k) => k === property.toLowerCase()) &&
          !newTranslations.results.some(
            (p) => p.label.toLowerCase() === translation.toLowerCase()
          )
        ) {
          notTranslatedKeys[property] = translation;
        }
      }

      fs.writeFileSync(
        `${objectType}-en-not-translated.json`,
        JSON.stringify(notTranslatedKeys, null, 2)
      );
    }
  } catch (err) {
    console.error(err);

    throw err;
  }
};

func();
